# This file shows the full simulation configuration for the `forklift` model of the `vog` robot.
# If you need to customize the simulation configuration, create a new file and pass it as a value
# for the parameter 'sim_file' in the used launch file.

# Plugin to control the mobile base in velocity.
base_velocity_controller:
  enabled: True
  topic: cmd_vel
  initial_linear_vel: { "x": 0.0, "y": 0.0, "z": 0.0 }
  initial_angular_vel: { "x": 0.0, "y": 0.0, "z": 0.0 }

base_pose_ground_truth_publisher:
  enabled: True
  fixed_frame: map
  offset: { "x": 0.0, "y": 0.0, "z": 0.0, "R": 0.0, "P": 0.0, "Y": 0.0 }
  global_offset: { "x": 0.0, "y": 0.0, "z": 0.0, "R": 0.0, "P": 0.0, "Y": 0.0 }
  gaussian_noise: 0.0
  publication_frequency: 50.0
  nav_topic_no_cov: base_pose_ground_truth_no_cov # published
  nav_topic_cov: base_pose_ground_truth # published
  tf_topic: tf_sim_world_fr_robot_root_fr # published

# Plugin to control the steering joint of the steerable wheel 0
base_steerable_wheel_0_steering_joint_controller:
  enabled: True
  initial_angle: 0.0
  topic: joint_commands/base # received

# Plugin to control the steering joint of the steerable wheel 1
base_steerable_wheel_1_steering_joint_controller:
  enabled: True
  initial_angle: 0.0
  topic: joint_commands/base # received

# Plugin to control the steering joint of the steerable wheel 2
base_steerable_wheel_2_steering_joint_controller:
  enabled: True
  initial_angle: 0.0
  topic: joint_commands/base # received

# Plugin to control the steering joint of the steerable wheel 3
base_steerable_wheel_3_steering_joint_controller:
  enabled: True
  initial_angle: 0.0
  topic: joint_commands/base # received

# Plugin to control the rotation of the steerable wheels.
# It has visual purposes only, since the motion of the platform is controlled by
# the base_velocity_controller.
# If disabled, the wheels will not rotate visually, but the platform will still
# move correctly.
base_steerable_wheel_0_rotation_joint_controller:
  enabled: True
  topic: joint_commands/base # received

base_steerable_wheel_1_rotation_joint_controller:
  enabled: True
  topic: joint_commands/base # received

base_steerable_wheel_2_rotation_joint_controller:
  enabled: True
  topic: joint_commands/base # received

base_steerable_wheel_3_rotation_joint_controller:
  enabled: True
  topic: joint_commands/base # received

# Plugin to control the fork in position.
fork_controller:
  enabled: True
  initial_position: 0.0
  topic: joint_commands/fork # received
  p_gain: 200.0
  i_gain: 5.0
  d_gain: 20.0
  i_max: 50.0
  i_min: -50.0
  cmd_max: 200.0
  cmd_min: -200.0
  cmd_offset: 0.0

# Plugin to publish the joint states of the robot.
joint_state_publisher:
  enabled: True
  topic: joint_states # published

################################################################################
# Fork camera is a RealSense D435
################################################################################
# In a physical RealSense D435, depth is estimated from the stereo pair captured by the two
# infrared cameras.
# In this simulation model, the color and depth streams are generated by a single 'rgbd_camera'
# Gazebo plugin, while the two infrared streams are generated by two separate 'camera' Gazebo
# plugins.

# Many of the values you find here can be obtained by running the binay:
# > rs-enumerate-devices <options>
# Find more information about the command and its options at
# https://github.com/realsenseai/librealsense/blob/master/tools/enumerate-devices/readme.md

# Configuration for a 'rgbd_camera' Gazebo plugin.
fork_camera_rgbd:
  enabled: True
  use_gravity: True
  always_on: True
  visualize: False
  enable_metrics: False
  save:
    enabled: False
    path: /tmp/fork_camera_rgbd
  triggered: False
  visible_mask: 4294967295
  clip:
    near: 0.1
    far: 10.0
  depth_clip:
    near: 0.1
    far: 10.0
  # These values follow the depth stream geometry used in the split D435 example.
  # The RGB image published by the RGBD sensor will still use image.format below.
  update_rate: 30.0
  image:
    width: 1280
    height: 720
    format: R8G8B8
    anti_aliasing: 4
  lens_single_elements:
    type: gnomonical # DO NOT CHANGE
    scale_to_hfov: True # DO NOT CHANGE
    cutoff_angle_deg: 90.0
    env_texture_size: 256
  # 'lens_custom_function' is not used, since it must be '' (empty string)
  lens_custom_function: ""
  # fx = (image_width_px/2) / tan(horizontal_fov/2) = (1280/2) / tan(90/2) = 640 / tan(45) = 640
  # fy = (image_height_px/2) / tan(vertical_fov/2)  = (720/2) / tan(63/2) = 360 / tan(31.5) = 588.2
  # cx = (image_width_px − 1) / 2 = (1280 − 1) / 2  = 639.5
  # cy = (image_height_px − 1) / 2 = (720 − 1) / 2  = 359.5
  lens_intrinsics:
    fx: 640.0
    fy: 588.2
    cx: 639.5
    cy: 359.5
  lens_xy_skew: 0.0
  # 'lens_projection' is not used, since it must be '' (empty string)
  lens_projection: ""
  distortion_k_p:
    k1: 0.0
    k2: 0.0
    k3: 0.0
    p1: 0.0
    p2: 0.0
  # center_x_norm = lens_intrinsics.cx + 0.5 / image.width = (639.5 + 0.5) / 1280 = 0.5
  # center_y_norm = lens_intrinsics.cy + 0.5 / image.height = (359.5 + 0.5) / 720 = 0.5
  # Use +0.5 to convert from pixel index to pixel center.
  distortion_center:
    center_x_norm: 0.5
    center_y_norm: 0.5
  gaussian_noise:
    mean: 0.0
    stddev: 0.0
  # The Gazebo plugin will publish the following topics:
  # Topic <base_topic>/image with messages of type gz.msgs.Image
  # Topic <base_topic>/depth_image with messages of type gz.msgs.Image
  # Topic <base_topic>/points with messages of type gz.msgs.PointCloudPacked
  # Topic <base_topic>/camera_info with messages of type gz.msgs.CameraInfo
  base_topic: fork_camera/rgbd
  # Use this topic if triggered is True. The Gazebo plugin will subscribe to this topic and capture
  # an image each time a message is published in it.
  # The message type should be gz.msgs.Empty, since the content of the message is not used.
  trigger_topic: fork_camera/rgbd/trigger

# The configuration for both infrared cameras should be the same.

# Configuration for a 'camera' Gazebo plugin.
fork_camera_infra1:
  enabled: False
  use_gravity: True
  always_on: True
  visualize: False
  enable_metrics: False
  save:
    enabled: False
    path: /tmp/fork_camera_infra1
  triggered: False
  visible_mask: 4294967295
  clip:
    near: 0.1
    far: 10.0
  # For a list of official supported modes for the infrared camera, see the comments in
  # robotics_description/config/sensors/cameras/example_realsense_d435_simulation.yaml
  update_rate: 30.0
  image:
    width: 1280
    height: 720
    format: L8
    anti_aliasing: 4
  lens_single_elements:
    type: gnomonical # DO NOT CHANGE: The infrared camera uses a gnomonical (aka pinhole) lens.
    scale_to_hfov: True # DO NOT CHANGE
    cutoff_angle_deg: 91.2
    # Resolution of the environment cube map used to draw the world.
    # The higher it is, the sharper the image.
    # Integer value.
    env_texture_size: 256
  # 'lens_custom_function' is not used, since it must be '' (empty string)
  lens_custom_function: ""
  # fx = (image_width_px/2) / tan(horizontal_fov/2) = (1280/2) / tan(91.2/2) = 640/tan(45.6) = 626.7
  # fy = (image_height_px/2) / tan(vertical_fov/2) = (720/2) / tan(65.5/2) = 360/tan(32.75) = 559.7
  # cx = (image_width_px − 1) / 2 = (1280 − 1) / 2 = 639.5
  # cy = (image_height_px − 1) / 2 = (720 − 1) / 2 = 359.5
  lens_intrinsics:
    fx: 626.7
    fy: 559.7
    cx: 639.5
    cy: 359.5
  lens_xy_skew: 0.0
  # 'lens_projection' is not used, since it must be '' (empty string)
  lens_projection: ""
  distortion_k_p:
    k1: 0.0
    k2: 0.0
    k3: 0.0
    p1: 0.0
    p2: 0.0
  # center_x_norm = lens_intrinsics.cx + 0.5 / image.width = (639.5 + 0.5) / 1280 = 0.5
  # center_y_norm = lens_intrinsics.cy + 0.5 / image.height = (359.5 + 0.5) / 720 = 0.5
  # Use +0.5 to convert from pixel index to pixel center.
  distortion_center:
    center_x_norm: 0.5
    center_y_norm: 0.5
  gaussian_noise:
    mean: 0.0
    stddev: 0.0
  image_topic: fork_camera/infra1/image # published
  camera_info_topic: fork_camera/infra1/camera_info # published
  # Use this topic if triggered is True. The Gazebo plugin will subscribe to this topic and capture
  # an image each time a message is published in it.
  # The message type should be gz.msgs.Empty, since the content of the message is not used.
  trigger_topic: fork_camera/infra1/trigger

# Configuration for a 'camera' Gazebo plugin.
fork_camera_infra2:
  enabled: False
  use_gravity: True
  always_on: True
  visualize: False
  enable_metrics: False
  save:
    enabled: False
    path: /tmp/fork_camera_infra2
  triggered: False
  visible_mask: 4294967295
  clip:
    near: 0.1
    far: 10.0
  # For a list of official supported modes for the infrared camera, see the comments in
  # robotics_description/config/sensors/cameras/example_realsense_d435_simulation.yaml
  update_rate: 30.0
  image:
    width: 1280
    height: 720
    format: L8
    anti_aliasing: 4
  lens_single_elements:
    type: gnomonical # DO NOT CHANGE: The infrared camera uses a gnomonical (aka pinhole) lens.
    scale_to_hfov: True # DO NOT CHANGE
    cutoff_angle_deg: 91.2
    # Resolution of the environment cube map used to draw the world.
    # The higher it is, the sharper the image.
    # Integer value.
    env_texture_size: 256
  # 'lens_custom_function' is not used, since it must be '' (empty string)
  lens_custom_function: ""
  # fx = (image_width_px/2) / tan(horizontal_fov/2) = (1280/2) / tan(91.2/2) = 640/tan(45.6) = 626.7
  # fy = (image_height_px/2) / tan(vertical_fov/2) = (720/2) / tan(65.5/2) = 360/tan(32.75) = 559.7
  # cx = (image_width_px − 1) / 2 = (1280 − 1) / 2 = 639.5
  # cy = (image_height_px − 1) / 2 = (720 − 1) / 2 = 359.5
  lens_intrinsics:
    fx: 626.7
    fy: 559.7
    cx: 639.5
    cy: 359.5
  lens_xy_skew: 0.0
  # 'lens_projection' is not used, since it must be '' (empty string)
  lens_projection: ""
  distortion_k_p:
    k1: 0.0
    k2: 0.0
    k3: 0.0
    p1: 0.0
    p2: 0.0
  # center_x_norm = lens_intrinsics.cx + 0.5 / image.width = (639.5 + 0.5) / 1280 = 0.5
  # center_y_norm = lens_intrinsics.cy + 0.5 / image.height = (359.5 + 0.5) / 720 = 0.5
  # Use +0.5 to convert from pixel index to pixel center.
  distortion_center:
    center_x_norm: 0.5
    center_y_norm: 0.5
  gaussian_noise:
    mean: 0.0
    stddev: 0.0
  image_topic: fork_camera/infra2/image # published
  camera_info_topic: fork_camera/infra2/camera_info # published
  # Use this topic if triggered is True. The Gazebo plugin will subscribe to this topic and capture
  # an image each time a message is published in it.
  # The message type should be gz.msgs.Empty, since the content of the message is not used.
  trigger_topic: fork_camera/infra2/trigger

################################################################################
